# Homeserver details.
homeserver:
    # The server name of the homeserver.
    domain: beeper.com
    # Client-server API URL.
    address: http://localhost:5000
    # Shared secret for login with https://github.com/devture/matrix-synapse-shared-secret-auth
    login_shared_secret:

# Application service registration related details.
# Changing these values requires regeneration of the registration.
appservice:
    # The address that the homeserver can use to connect to this appservice.
    # The listen host/port are defined in the mux section below.
    address: http://0.0.0.0:29326

    # The unique ID of this appservice.
    id: asmux
    # Username of the appservice bot. This isn't currently used for anything, but needs to be set.
    bot_username: asmuxbot
    # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
    # to leave display name/avatar as-is.
    bot_displayname: mautrix-asmux
    bot_avatar:

    # Authentication tokens for asmux <-> HS communication. Autogenerated; do not modify.
    as_token: anything-will-do
    hs_token: anything-will-do

    namespace:
        # Prefix used for all username and alias namespaces.
        prefix: _
        # Whether or not the prefix should be exclusively for asmux (and the services behind it).
        exclusive: true

segment:
    token:
    host: api.segment.io

metrics:
    enabled: true
    listen_port: 8000

# Main mautrix-asmux settings
mux:
    # The hostname and port where this appservice should listen.
    # This is both the server where synapse sends AS transactions and the server where bridges
    # should connect to use the client-server API.
    hostname: 0.0.0.0
    port: 29326
    # Database URI. Currently only supports postgres://user:password@host/dbname
    database: postgres://postgres@localhost:5432/postgres
    # Public address to reach asmux
    public_address: https://asmux.example.com
    # Shared secret for accessing the API
    shared_secret: r5jtfhkvf03d0nyyuhru4l0cq3ov7n5aymidb3p71e35p54ajiwqqrcab6a7hfd4
    # Config template files for embedded bridges like iOS iMessage
    bridge_config_template_files: {}
    # Endpoint for reporting bridge status.
    # Currently used for reporting transaction websocket disconnections.
    remote_status_endpoint:
    bridge_status_endpoint:
    # Endpoint for reporting per-message status.
    message_send_checkpoint_endpoint:
    # Settings for mautrix-syncproxy to do encryption-related /syncing in the cloud.
    sync_proxy:
        # Address where mautrix-asmux can reach the sync proxy.
        url:
        # Shared secret for sync proxy API.
        token:
        # Address where the sync proxy can reach mautrix-asmux.
        asmux_address:

# Python logging configuration.
#
# See the configuration dictionary schema in the Python documentation for more info:
# https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
logging:
    version: 1
    formatters:
        colored:
            (): mautrix.util.color_log.ColorFormatter
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
        normal:
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: normal
            filename: ./mautrix-asmux.log
            maxBytes: 10485760
            backupCount: 10
        console:
            class: logging.StreamHandler
            formatter: colored
    loggers:
        mau:
            level: DEBUG
        aiohttp:
            level: INFO
    root:
        level: DEBUG
        handlers: [file, console]
