build:
  stage: build
  needs: []
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - if [ $CI_COMMIT_BRANCH == "master" ]; then
      docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest;
      docker push $CI_REGISTRY_IMAGE:latest;
      fi

lint:
  stage: test
  needs: []
  image: python:latest
  before_script:
    - pip install -r dev-requirements.txt
    - pip install .
  script:
    - pre-commit run -av trailing-whitespace
    - pre-commit run -av end-of-file-fixer
    - pre-commit run -av check-yaml
    - pre-commit run -av check-added-large-files
    - black --check --diff --fast mautrix_asmux/
    - isort --check-only --diff mautrix_asmux/
    # TODO: this exclude should not be required as it's in pyproject.toml
    - mypy --exclude "mautrix_asmux/database/upgrade/*" mautrix_asmux/
