build:
  stage: build
  needs: []
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - if [ $CI_COMMIT_BRANCH == "master" ]; then
      docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest;
      docker push $CI_REGISTRY_IMAGE:latest;
      fi

lint:
  stage: test
  needs: []
  image: python:3.9-alpine
  before_script:
    - pip install black isort
  script:
    - black --check --diff --fast mautrix_asmux/
    - isort --check-only --diff mautrix_asmux/
